# TIL

## 계산기 과제 트러블슈팅(예외처리 및 클래스 분리)

## 문제 상황
- `Calculate` 클래스에는 연산을 하는 `calculate` 메서드 외에도 연산 결과들을 저장하고 제어하는 여러 메서드가 포함되어 있었고,  
`CalculatorResult` 클래스를 새로 만들어 연산 결과를 저장하는 `results` 컬렉션 필드 및 그와 관련된 제어 메서드들을 이쪽으로 이동함.
- `calculate()` 메서드 안에서 `try-catch` 블록을 사용해 연산 오류(잘못된 연산기호, 0으로 나누기 등)를 처리하고,  
 `flag`방식을 통해 정상/비정상을 판별하여 문제가 없으면 `result` 값을 저장, 문제가 있으면 저장하지 않음.
- **기존에는 클래스 안에서 `result`값을 `results`에 저장해주면 되었는데 분리 이후에는 `return`을 해줘야했고  
`try-catch`로 예외를 내부에서 처리하면서, 연산 과정이 비정상일시에 `return`을 어떻게 처리할지 고민함.**

## 해결 과정
- 내부에서 예외를 잡고 다시 `throw`로 예외 던지기를 하는 방식은 코드 흐름이 복잡하고 지저분하다고 생각하여서 다른 방식을 선택하고자 하였다.
- 예외는 메서드 내부에서 처리하지 않고, 호출자(main)에서 처리하는 게 제일 깔끔하다고 생각하였고  
`calculate()` 메서드에서 `throws` 키워드를 사용하여 예외를 메서드를 호출한 `main`으로 전파하였다.

## 최종 해결 방법
`main`에서 `try-catch`로 예외를 한 곳에서 일괄 처리하고 try안에 `calResult.addResult(result)`를 넣어 연산에 문제가 없을 경우에만 결과를 저장
```java
try {
                double num1 = sc.nextDouble();
                System.out.print("두 번째 숫자를 입력하세요 : ");
                double num2 = sc.nextDouble();
                System.out.print("사칙연산 기호를 입력하세요(+,-,*,/) : ");
                char oper = sc.next().charAt(0);
                sc.nextLine();
                // static 연산 메서드 호출
                double result = Calculator.calculate(num1, num2, oper);
                calResult.addResult(result);
            } catch (InputMismatchException e) {
                System.out.println("입력이 잘못되었습니다.");
                sc.nextLine();
                continue;
            } catch (ArithmeticException e) {
                System.out.println("나눗셈 연산에서 두 번째 숫자에 0이 입력될 수 없습니다.");
                continue;
            } catch (IllegalArgumentException e) {
                System.out.println("잘못된 사칙연산 기호입니다.");
                continue;
            }
```
## 배운점
- 예외는 발생한 곳에서 처리하기보다, 호출한 쪽으로 던져서 일괄 처리하는 게 더 구조적이고 명확하다.
- 클래스를 기능별로 분리하고 예외를 일괄 처리하면서, 유지보수성 및 가독성 등이 개선되었다.
